[build]
  base = "stock-frontend"
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--include=dev"
  NODE_OPTIONS = "--max_old_space_size=4096"
  VITE_API_URL = "https://stock-market-26i6.onrender.com/api"

[[redirects]]
  from = "/api/*"
  to = "https://stock-market-26i6.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
